USE [FG]
GO

SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;

IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_Cu_Min') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_Cu_Min decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielCuMin DEFAULT 0;
IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_Cu_Max') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_Cu_Max decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielCuMax DEFAULT 999;

IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_Mn_Min') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_Mn_Min decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielMnMin DEFAULT 0;
IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_Mn_Max') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_Mn_Max decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielMnMax DEFAULT 999;

IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_C_Min') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_C_Min decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielCMin DEFAULT 0;
IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_C_Max') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_C_Max decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielCMax DEFAULT 999;

IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_Si_Min') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_Si_Min decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielSiMin DEFAULT 0;
IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_Si_Max') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_Si_Max decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielSiMax DEFAULT 999;

IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_Cr_Min') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_Cr_Min decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielCrMin DEFAULT 0;
IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_Cr_Max') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_Cr_Max decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielCrMax DEFAULT 999;

IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_Mg_Min') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_Mg_Min decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielMgMin DEFAULT 0;
IF COL_LENGTH(N'dbo.FALCOM_MATERIAL', N'Ziel_Mg_Max') IS NULL
   ALTER TABLE dbo.FALCOM_MATERIAL ADD Ziel_Mg_Max decimal(10,3) NOT NULL CONSTRAINT DF_FALCOM_MATERIAL_ZielMgMax DEFAULT 999;

EXEC sp_executesql N'
UPDATE dbo.FALCOM_MATERIAL
   SET Ziel_Cu_Min = Cu_Min,
       Ziel_Cu_Max = Cu_Max,
       Ziel_Mn_Min = Mn_Min,
       Ziel_Mn_Max = Mn_Max
WHERE Ziel_Cu_Min = 0
  AND Ziel_Cu_Max = 999
  AND Ziel_Mn_Min = 0
  AND Ziel_Mn_Max = 999;';

COMMIT TRANSACTION;
GO
