USE [FG]
GO

SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;

IF COL_LENGTH(N'dbo.FALCOM_LAGER', N'MaterialID') IS NULL
BEGIN
   THROW 51000, 'Spalte MaterialID existiert in dbo.FALCOM_LAGER nicht.', 1;
END;

ALTER TABLE dbo.FALCOM_LAGER ALTER COLUMN MaterialID bigint NULL;

UPDATE dbo.FALCOM_LAGER
   SET MaterialID = NULL
WHERE PlatzTyp = N'LKW_PLATZ'
   OR Lagerplatz IN (101,102,103);

COMMIT TRANSACTION;
GO
