USE [FG]
GO

SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;

IF OBJECT_ID(N'dbo.FALCOM_AKTUELLE_FAHRT', N'U') IS NULL
   AND OBJECT_ID(N'dbo.FALCOM_KRAN_QUEUE', N'U') IS NOT NULL
BEGIN
   EXEC sp_rename N'dbo.FALCOM_KRAN_QUEUE', N'FALCOM_AKTUELLE_FAHRT';
END

IF OBJECT_ID(N'dbo.FK_FALCOM_KRAN_QUEUE_QuellePosition', N'F') IS NOT NULL
   EXEC sp_rename N'dbo.FK_FALCOM_KRAN_QUEUE_QuellePosition', N'FK_FALCOM_AKTUELLE_FAHRT_QuellePosition', N'OBJECT';

IF OBJECT_ID(N'dbo.FK_FALCOM_KRAN_QUEUE_ZielPosition', N'F') IS NOT NULL
   EXEC sp_rename N'dbo.FK_FALCOM_KRAN_QUEUE_ZielPosition', N'FK_FALCOM_AKTUELLE_FAHRT_ZielPosition', N'OBJECT';

IF OBJECT_ID(N'dbo.CK_FALCOM_KRAN_QUEUE_Status', N'C') IS NOT NULL
   EXEC sp_rename N'dbo.CK_FALCOM_KRAN_QUEUE_Status', N'CK_FALCOM_AKTUELLE_FAHRT_Status', N'OBJECT';

IF OBJECT_ID(N'dbo.DF_FALCOM_KRAN_QUEUE_Status', N'D') IS NOT NULL
   EXEC sp_rename N'dbo.DF_FALCOM_KRAN_QUEUE_Status', N'DF_FALCOM_AKTUELLE_FAHRT_Status', N'OBJECT';

IF OBJECT_ID(N'dbo.FK_FALCOM_KRAN_COMMAND_LOG_Queue', N'F') IS NOT NULL
   EXEC sp_rename N'dbo.FK_FALCOM_KRAN_COMMAND_LOG_Queue', N'FK_FALCOM_KRAN_COMMAND_LOG_AktuelleFahrt', N'OBJECT';

COMMIT TRANSACTION;
GO
